---
title: "Events"
---

## <span style="background-color: #d1dce5;">September 2025</span>

### 📌 GLE$^2$N invited lecture: Professor Brian Reich

Gertrude M. Cox Distinguished Professor [Brian Reich](https://bjreich.wordpress.ncsu.edu/) will deliver an invited lecture at GLEN in September. More details will be available online soon.



### 📌 Two RSS sessions on extremes

We’re excited to announce that the RSS Conference 2025 will feature two invited sessions on extreme value theory. The conference will be held at the Edinburgh International Conference Centre from 1–4 September. Find more details [here](https://rss.org.uk/training-events/conference-2025/). See below for information on the two organised sessions.


#### 1. Advancing Statistical Frontiers: Extreme Value Theory, Machine Learning, and Point Processes

**Day and time**: Tuesday 2nd September 2025, 15:00 - 16:20

**Summary**

This session explores the intersection of extreme value theory, machine learning, and point processes, showcasing how modern statistical methodologies can address complex, real-world phenomena characterised by rare and extreme events.
The session will cover topics such as spatial confounding, preferential sampling, marked point processes, and neural estimation for extremal processes with complex dependencies.
This session is designed for statisticians, data scientists, and researchers interested in discovering the potential of blending traditional and machine learning approaches to tackle challenges in spatio-temporal modelling.

**Invited speakers**

- **Ottmar Cronie** (department of Mathematical Sciences, Chalmers University of Technology & University of Gothenburg, Sweden). ***Some new results on marked point processes and their statistical applications***.
- **Brian Reich** (department of Statistics, North Carolina State University). ***Spatial confounding and preferential sampling***
- **Julia Walchessen** (department of Statistics & Data Science, Carnegie Mellon University). ***Neural Conditional Simulation for Complex Spatial Processes***

**Organisers**: Daniela Castro-Camilo, Amanda Lenzi and Jorge Mateu.


#### 2. Practical methodologies for multivariate extremes

**Day and time**: Thursday 4th September, 11.30am – 12.50pm

**Summary**
We would like to propose a session at RSS 2025 on emerging methodologies for multivariate extreme value analysis, in particular methodologies based on angular-radial representations of data, gauge theory and limit sets. These methodologies offer statistically sound but also intuitively attractive and practically feasible routes to applied extreme value analysis, especially for environmental applications in higher dimensions. In our opinion, a discussion of these developments would provide a worthwhile session at RSS2025. 

We intend to co-ordinate the presentations so that the audience is provided with a reasonable overview of the underpinning methodology and its practical real-world application. All presenters and proponents of the session have published recently on the methodology and/or its applications, including: Nolde and Wadsworth [[2022]](https://www.cambridge.org/core/journals/advances-in-applied-probability/article/linking-representations-for-multivariate-extremes-via-a-limit-set/9A77F8E10602DC13EA26E429CFB5FD21), Huser and Wadsworth [[2022]](https://wires.onlinelibrary.wiley.com/doi/10.1002/wics.1537), Mackay et al. [[2025]](https://asmedigitalcollection.asme.org/offshoremechanics/article-abstract/147/1/011205/1201564/The-SPAR-Model-A-New-Paradigm-for-Multivariate?redirectedFrom=fulltext), Murphy-Barltrop et al.[[2024]](https://link.springer.com/article/10.1007/s10687-024-00492-2), Richards and Huser [[2024]](https://arxiv.org/abs/2208.07581), Simpson and Tawn [[2024]](https://link.springer.com/article/10.1007/s13253-024-00612-2) and Wadsworth
and Campbell [[2024]](https://watermark.silverchair.com/qkae030.pdf?token=AQECAHi208BE49Ooan9kkhW_Ercy7Dm3ZL_9Cf3qfKAc485ysgAAA2UwggNhBgkqhkiG9w0BBwagggNSMIIDTgIBADCCA0cGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMEsZtlRy3OPoT1pcNAgEQgIIDGLtL0XyrZNmOe1wZNIPOtMuwX5BxYonBWvYgqAthocg4qs0OEaYvIu9P7GijjQQpT6A03xLZ2JXFiwhIIeUY-wvVWdV8BYlQEKfZrNuPFK7_EoxxzAYa-MtCNYEoEVbKp0_zXsOjmXygj7atVo7jIDqX1GqQHgzk7F-sMjf41xBAgonh0hcxv5CVqWP9p_eaaAy4K-ZtZ95MqLzO3NGy7EQ4iigXwEHtpeWVoej04dDT7uxCcvTHJBiW1rYF18Rud43cmQNZ8gzcorCUAoVcOo1Lln7jHUWVdzu5RjjHMfwGyJVyz6GMp_t3l1G8jbNSA1DpITVLDFTiK9R-HZejwdfnonJ5231WOVjsw2mTixskAOtLX55Y_AAH9NSUoVAdbgfASnowV6rl_Af-C_SV5p8oCXzY2cHxUwhf8KHJ-9R5Z_HrWJOaeZz5_IsIzm0qZOHfYx1IvkLHdUn3s7n_SHWBzDWM0Xfh0Kbdsv1zRmL_wVO0QfOSBue9eHVlMjC5hZf3qr2a9-feokpThgOzU4obhHJLOSR83dvZYdrunmZZZxDK2HJ18mAKGgM9wrDNIK9bJhI3rGaHuNZe8WMf_OKXsEMGPJTde0Uj7c2LPUq57yeGFgAkIBWQKcwUMNRokqNU4-rqP-lJTH7Hbroa6NdC7Ear1yD2sKuGexvjq4UA8LisGHjpo9WUNoaolJVqR1ZtxNOJOdGp5vgEiXG7nIBBId_ad-Trk5JmDWtM4vtoNkPH_VOqHWRwi7qmXn6994BCUo9xqgc8cgceLBGr2sWSPJ_0T436w13L0lsYdWumUD1gxJdA9DIzYSX3eU9I-VcS4n5IM_CUbjY5YjxFPJlvMamSZhWGO78WsYJwYQpZdlOA4fq4q3CfXclIwn6Wzn2dZS45shdP1jEZdly0_5nvwFdMPwUFnoQVj3M7rypML5l7Kb-3uI_wdo3-wXO3hMT4sSl308Ay8byWUj5a_qy_PXSGAUQWXnN-FzcLVmPA_aL4ViDlrUijW5wa7zwIu3_Du176LPl1kZDtbCd0zoJ6_-irNbj2Lg).


**Invited speakers**

- **Jenny Wadsworth** (School of Mathematical Sciences, Lancaster)

- **Emma Simpson** (Department of Statistical Science, UCL) 

- **Ed Mackay or Jordan Richards** (University of Exeter, University of Edinburgh, UK)

**Organisers**: C. Murphy-Barltrop, E. Mackay, J. Richards and P. Jonathan.


## <span style="background-color: #d1dce5;">June 2025</span>


### 📌 Workshop: Generative AI Modeling for Extreme Events

GLE$^2$N is organising a Workshop on **Generative AI Modeling for Extreme Events**, to be held during the week of the 9$^\text{th}$ of June. Further details will be available online soon.


## <span style="background-color: #d1dce5;">May 2025</span>

### 📌 GLE$^2$N at the INLA: past, present, and future workshop

GLE$^2$N member Chenglei Hu will be presenting a poster at the upcoming workshop [INLA: past, present, and future](https://inla-workshop.github.io/INLA-PastPresentFuture/). For scheduling information, please visit the workshop website—and read on for details about Chenglei’s presentation.

**Title**: From XGBoost to INLA: a two-stage spatio-temporal modeling of wildfire in Portugal via the extended generalised Pareto distribution

**Abstract**:

Wildfires pose a major threat to Portugal, with an average of over 90,000 hectares burned annually in recent decades. Beyond high wildfire frequency, the country has experienced devastating mega-fires, such as those in 2017. Accurate forecasting of wildfire occurrence and burned areas is therefore essential for effective firefighting resource allocation and emergency preparedness. In this study, we introduce a novel two-stage ensemble model that combines XGBoost and a spatial-temporal latent Gaussian model to jointly estimate the wildfire occurrence and burn area. Initially, XGBoost identifies wildfire patterns based on meteorological covariates, coordinates, and time indicators, and its predictions are subsequently enhanced by a spatial-temporal latent Gaussian model. Our results demonstrate that this ensemble approach outperforms either method individually. To effectively model both moderate and extreme wildfire events, we employ the extended Generalized Pareto distribution (eGPD), which features a gamma-like lower bound and a Pareto-like tail. The Gradient descent algorithm is used to estimate the XGBoost and Bayesian inference is conducted for the latent Gaussian model using Integrated Nested Laplace Approximation (INLA). Additionally, we contribute to the INLA community by implementing eGPD as a likelihood function in the R-INLA package and discussing its penalized Complexity priors (PC-priors).


## <span style="background-color: #d1dce5;">April 2025</span>

### 📌 GLE$^2$N-sponsored UofE Stats seminar: Ed Mackay (University of Exeter)

**Day and time**: Tuesday 8th April 2025, 15:00-16:00


**Location**: JCMB 5328 and online via [Zoom](https://ed-ac-uk.zoom.us/j/83049104036) (Meeting ID: 830 4910 4036 - Passcode: xZHq6w8t)

**Title**: Teaching an old dog new tricks: Extending univariate extreme value theory to multivariate problems

**Abstract** 

Various problems in civil engineering, risk assessment, and finance require estimates of the probabilities of various combinations of rare events. Whilst the theory of univariate extreme value statistics is relatively mature, there are still significant gaps in the theory of multivariate extremes. Many of the existing models are limited in terms of the types of joint distributions they can represent. Some models are only applicable in the region where all variables are large, whereas other methods are based on strong assumptions about the strength of dependence in the joint tails. This talk will show how univariate extreme value theory can be extended in two different ways to model multivariate extremes. In the first approach, known as the SPAR method [1-4], variables are transformed to angular and radial coordinates. After this transformation, the problem of modelling multivariate extremes is transformed to one of modelling an angular density and the tail of the radial variable, conditional on angle. We show that many existing approaches are special cases of this model, but that the SPAR framework provides greater flexibility than available with existing approaches. The second approach, known as Direct-IFORM [5], can be used to estimate half-space depth contours at extreme levels, which are routinely used for risk analysis in offshore engineering. The method has the advantage that it can be applied in any number of dimensions without loss without degradation in performance, lifting the so-called ‘curse of dimensionality’. Both methods make use of the univariate peaks-over-threshold method, giving a rigorous and asymptotically justified means for extrapolating outside the range of observations. In this talk we will give a brief introduction to theory and inference, as well as examples of their application to real-world datasets.

References:

1. E. Mackay and P. Jonathan, “Modelling multivariate extremes through angular-radial decomposition of the density function,” https://arxiv.org/abs/2310.12711

2. C. Murphy-Barltrop, E. Mackay, and P. Jonathan, “Inference for bivariate extremes via a semi-parametric angular-radial model,” Extremes, pp. 1–30, 2024.

3. E. Mackay, C. Murphy-Barltrop, P. Jonathan, “The SPAR model: A new paradigm for multivariate extremes. Application to joint distributions of metocean variables,” J. Offshore Mechanics and Arctic Engineering, vol. 147, p. 011205, 2025.

4. E. Mackay, C. Murphy-Barltrop, J. Richards, P. Jonathan, “Deep learning joint extremes of metocean variables using the SPAR model” https://arxiv.org/abs/2412.15808

5. E. Mackay, G. de Hauteclocque, “Model-free environmental contours in higher dimensions,” Ocean Engineering, vol. 273, p. 113959, 2023.



## <span style="background-color: #d1dce5;">February 2025</span>


### 📌 Jordan talk at RSS Edinburgh Local Group + R-Edinburgh meeting

The first RSS Edinburgh Local Group event of 2025, held in collaboration with the R-Edinburgh community will welcome two speakers, Isabella Deutsch and Jordan Richards, who will discuss Bayesian Statistics in the R programming language. 

**Day and time**: Thursday 27th February 2025, 18:00-19:30


**Location**: LG.11 40 George Square, The University of Edinburgh, EH8 9LX 

**Title**: Fast and Amortised Bayesian Inference with NeuralEstimators 

**Abstract** 

Neural estimators are neural networks that transform data into parameter point estimates. These estimators are likelihood-free and amortised, in the sense that, after an initial setup cost, inference from observed data can be made in a fraction of the time required by conventional approaches, e.g., MCMC or maximum likelihood estimation. They are also approximate Bayes estimators and, therefore, are often referred to as neural Bayes estimators. We present the user-friendly R package NeuralEstimators, which interfaces with the Julia package NeuralEstimators.jl, and allows for the development and application of neural Bayes estimators. This package caters for any model for which simulation is feasible by allowing the user to implicitly define their model via simulated data. No likelihood or long MCMC chains required! 

More information [here](https://rss.org.uk/training-events/events/events-2025/local-groups/no-likelihood-no-problem!-%E2%80%94-bayesian-statistics-in/#speakers).


---

### 📌 GLE$^2$N-sponsored UofE Stats seminar: Ilaria Prosdocimi and Isadora Antoniano Villalobos (Ca' Foscari University of Venice)

The UofE Stats seminar taking place the last week of February is a joint venture with GLE$^2$N. See details below.

**Day and time**: Monday 24th February 15:00

**Location**: JCMB 5323 and online via [Zoom](https://ed-ac-uk.zoom.us/j/83049104036) (Meeting ID: 830 4910 4036 -- Passcode: xZHq6w8t)

**Title**: 
Modelling non-stationarities in extreme hourly precipitation

**Abstract** 

Understanding spatiotemporal features of extremal precipitation is an essential component of hydrological risk management, for example in flood risk assessment. This study investigates and compares the performance of recently proposed multivariate extreme value models in describing such features, while allowing for spatial variation, temporal non-stationarity and different extremal dependence regimes.
We analyse data on hourly precipitation recorded at 65 sites in the period 1990–2023 across the Piave river basin in Northeastern Italy. Empirical evidence suggests that both the extremal dependence structures and the marginal behaviours of precipitation events vary throughout the year, reflecting seasonal patterns. Furthermore spatial dependence appears to weaken as precipitation events become more extreme. We investigate possible exogenous factors by introducing climatic variables as predictors for the marginal distributions, the spatial dependence and the interplay between them. We observe that capturing these features is essential to provide a realistic description of extreme precipitation processes in order to better estimate the risks associated with them. 

More information [here](https://www.maths.ed.ac.uk/school-of-mathematics/events/statistics).

