---
title: "News"
---

## <span style="background-color: #d1dce5;">February 2025</span>


### 📌 Jordan talk at RSS Edinburgh Local Group + R-Edinburgh meeting

The first RSS Edinburgh Local Group event of 2025, held in collaboration with the R-Edinburgh community, will feature Jordan presenting NeuralEstimators—an R package designed for the intuitive development of neural point estimators. These estimators, implemented as neural networks, map data to a point summary of the posterior distribution, offering a likelihood-free and amortised approach to inference. Once trained, they enable rapid inference from observed data, significantly reducing computation time compared to traditional methods.

This in-person event will take place on **Thursday, 27 February 2025, from 6:00 PM to 7:30 PM at the University of Edinburgh**. More details can be found [here](https://rss.org.uk/training-events/events/events-2025/local-groups/no-likelihood-no-problem!-%E2%80%94-bayesian-statistics-in/#speakers).


---

### 📌 UofE Stats seminar: Ilaria Prosdocimi and Isadora Antoniano Villalobos (Ca' Foscari University of Venice)

Ilaria and Isadora will be speaking at the University of Edinburgh School of Mathematics Statistics seminar. This will be a hybrid event. To attend online, please contact Jordan.

**Day and time**: 24th February 15:00

**Title** 
Modelling non-stationarities in extreme hourly precipitation

**Abstract** 
Understanding spatiotemporal features of extremal precipitation is an essential component of hydrological risk management, for example in flood risk assessment. This study investigates and compares the performance of recently proposed multivariate extreme value models in describing such features, while allowing for spatial variation, temporal non-stationarity and different extremal dependence regimes.
We analyse data on hourly precipitation recorded at 65 sites in the period 1990–2023 across the Piave river basin in Northeastern Italy. Empirical evidence suggests that both the extremal dependence structures and the marginal behaviours of precipitation events vary throughout the year, reflecting seasonal patterns. Furthermore spatial dependence appears to weaken as precipitation events become more extreme. We investigate possible exogenous factors by introducing climatic variables as predictors for the marginal distributions, the spatial dependence and the interplay between them. We observe that capturing these features is essential to provide a realistic description of extreme precipitation processes in order to better estimate the risks associated with them. 


## <span style="background-color: #d1dce5;">November 2024</span>

### 📌 Environmental and Ecological Statistics Conference 2025
 
EnvEcoStats, the Environmental and Ecological Statistics Conference, will take place in Lancaster from 1–3 July 2025. Co-organized by the University of Glasgow and Lancaster University, it serves as a satellite event to the ISI World Statistics Congress 2025 and is sponsored by TIES and the Environmental Statistics Section of the Royal Statistical Society.  

Building on the success of previous workshops in 2023 and 2024, the conference aims to foster collaboration between environmental and ecological statisticians, support knowledge exchange, and connect academics, data scientists, and NGOs.  

The three-day program will feature 

- Keynote talks
- Invited talks
- A panel discussion on "Climate Change and Disaster-related Statistics" 
- Contributed sessions
- Poster session with flash presentations
- Best contributed talk and best poster awards

**Registration and abstract submissions for contributions are now open, along with submissions for invited session proposals**. Please submit your contribution [here](https://envecostats.wordpress.com/). For any questions or further information, please contact us at envecostats@googlegroups.com. 

---

### 📌 Call for Papers: Bridging Heavy Tails & AI - Extremes (Springer)
Invited special issue of Extremes, focusing on bridging Artificial Intelligence (AI) and Extreme Value Theory (EVT). This issue aims to unite the strengths of both fields to tackle the growing challenges of extreme events.

Extremes, published by Springer, is the world-leading journal on EVT and its applications across diverse fields.
We welcome submissions on topics such as:

- Interfaces between regularly-varying tails and machine learning
- Neural architectures for modeling heavy-tailed phenomena
- Explainability of machine learning models for extremes
- Generative models for extreme events
- Online learning methods for extreme events

The submission deadline is **March 30, 2025**. Manuscripts should be submitted  [here](https://link.springer.com/journal/10687/updates).

Guest Editors: Miguel de Carvalho & Jordan Richards