---
title: "People"
---

::: {.grid}

::: {.g-col-6}

## Founders
- [Daniela Castro-Camilo](https://www.gla.ac.uk/schools/mathematicsstatistics/staff/danielacastrocamilo/) (UofG)
- [Jordan Richards](https://jbrich95.github.io/) (UofE)
- [Miguel de Carvalho](https://www.maths.ed.ac.uk/~mdecarv/) (UofE)
- [Ioannis Papastathopoulos](https://www.maths.ed.ac.uk/~ipapasta/) (UofE)

:::
  
::: {.g-col-6}

## Reading Group Organisers 2025-26

- [Mengran Li](https://mengranli.netlify.app/) (UofG)
- [Johnny Myung Won Lee](https://johnnymdoubleu.github.io/) (UofE)

## Reading Group Organisers 2024-25

- [Chenglei Hu](https://www.gla.ac.uk/pgrs/chengleihu/) (UofG)
- [Johnny Myung Won Lee](https://johnnymdoubleu.github.io/) (UofE)

:::
  
:::  

## Current contributors

  - [Mengran Li](https://mengranli.netlify.app/) (UofG)
  - [Chenglei Hu](https://www.gla.ac.uk/pgrs/chengleihu/) (UofG)
  - [Johnny Myung Won Lee](https://johnnymdoubleu.github.io/) (UofE)
  - [Lambert de Monte](https://www.maths.ed.ac.uk/school-of-mathematics/people/a-z?person=1089) (UofE)
  - [Prof Sergey Foss](https://researchportal.hw.ac.uk/en/persons/sergey-foss) (HW)
  - [Prof Andrew Cairns](https://www.macs.hw.ac.uk/~andrewc/) (HW)
  - [Dr Seva Shneer](https://www.macs.hw.ac.uk/~vs128/) (HW)
  - [Dr Daniela Escobar](https://researchportal.hw.ac.uk/en/persons/debora-daniela-escobar) (HW)
  - [Dr Alfred Chong](https://researchportal.hw.ac.uk/en/persons/alfred-chong) (HW)
  - [Prof George Streftaris](https://www.macs.hw.ac.uk/~georges/) (HW)
  - [Dr Giovanni Rabitti](https://researchportal.hw.ac.uk/en/persons/giovanni-rabitti) (HW)
  - [Prof Catherine Donnelly](http://www.ma.hw.ac.uk/~cd134/) (HW)
  - [Dr Timothy Johnson](https://researchportal.hw.ac.uk/en/persons/timothy-johnson) (HW)
  - [Prof Victor Elvira](https://victorelvira.github.io/) (UofE)
  - [Linlu Zhao](https://www.maths.ed.ac.uk/school-of-mathematics/people/a-z?person=1362) (UofE)
  - [Xindi Song](https://maths.ed.ac.uk/people/phd?person=1237) (UofE)
  - [Teng Wei Yeo](https://www.gla.ac.uk/pgrs/tengweiyeo/#supervisors) (UofG)

- [Emma Eastoe](https://www.lancaster.ac.uk/maths/people/emma-eastoe) (LU)

- [Jenny Wadsworth](https://www.lancaster.ac.uk/~wadswojl/) (LU)

- [Sylwia Bathe-Taylor]() (LU)

- [Kristina Grolmosova](https://www.lancaster.ac.uk/maths/people/kristina-grolmusov%C3%A1) (LU)

- [Kristina Bratkova](https://www.lancaster.ac.uk/maths/people/kristina-bratkova) (LU)

- [Kajal Dodhia](https://www.lancaster.ac.uk/sci-tech/about-us/people/kajal-dodhia) (LU)

- [Lydia Kakampakou](https://www.lancaster.ac.uk/maths/people/lydia-kakampakou) (LU)

- [Vianey Palacios Ramirez](https://www.ncl.ac.uk/maths-physics/people/profile/vianeypalacios-ramirez.html) (NU)



## Affiliated and honorary members

- [Yandira Cuvero](https://scholar.google.com/citations?user=7pfic1MAAAAJ&hl=es)
- [Léo Belzille](https://www.hec.ca/en/profs/leo-belzile)
