---
title: "Research talks"
---
```{r setup, include=FALSE}
library(knitr)
library(kableExtra)
library(dplyr)
knitr::opts_chunk$set(
  message = FALSE, 
  warning = FALSE,
  fig.align = "center",
  cache = F
)

```

The second part of each GLE$^2$N meeting features a research talk, providing an opportunity for a member to showcase ongoing research or explore new ideas through group discussion.


## Talks  🗣️
::: {.callout-tip collapse="true" appearance="simple" icon=false}
# <span style="color: rgb(25,188,156)">17/10/25</span>  Causal Spatial Quantile Regression by Yan Gong (MBZUAI)

**Summary**
Treatment effects in a wide range of economic, environmental, and epidemiological applications often vary across space, and understanding the heterogeneity of causal effects across space and outcome quantiles is a critical challenge in spatial causal inference. To effectively capture spatial heterogeneity in distributional treatment effects, we propose a novel semiparametric neural network-based causal framework leveraging deep spatial quantile regression and then construct a plug-in estimator for spatial quantile treatment effects (SQTE). This framework incorporates an efficient adjustment procedure to mitigate the impact of spatial hidden confounders. Extensive simulations across various scenarios demonstrate that our methodology can accurately estimate SQTE, even with the presence of spatial hidden confounders. Additionally, the spatial confounding adjustment procedure effectively reduces neighborhood spatial patterns in the residuals. We apply this method to assess the spatially varying quantile treatment effects of maternal smoking on newborn birth weight in North Carolina, United States. Our findings consistently show negative effects across all birth weight quantiles, with particularly severe impacts observed in the lower quantile regions.

 
**Joint work with:**  R. Majumder, B. J. Reich, R. Huser


:::

::: {.callout-tip collapse="true" appearance="simple" icon=false}
# <span style="color: rgb(25,188,156)">17/10/25</span>  Modelling non-stationary extremal dependence through a geometric approach by Callum Murphy-Barltrop (TU Dresden)

**Summary**
In many environmental and financial datasets, the relationships between extremes of multiple variables change over time — a phenomenon known as non-stationary, or time-varying, extremal dependence. The majority of multivariate extreme value models (MEVMs) fail to account for such trends, motivating the need for novel developments.

Many recent MEVMs utilise the geometric extremes framework, whereby extremal dependence features are inferred from the limiting shapes of scaled sample clouds. Such approaches possess many attractive features; for example, they can capture a wide range of dependence structures and can be used to estimate many practically relevant quantities.

In this work, we extend the geometric extremes framework to capture time-varying extremal dependence. Our proposed framework is more flexible compared to many existing non-stationary MVEMs and offers a wide variety of interesting use cases. Through rigorous simulation studies, we demonstrate that our proposed framework is both robust and accurate. To conclude, we apply our framework to return data from 'The Magnificent 7,' a group consisting of the world's largest technology companies.

 
**Joint work with:** J. Wadsworth, M. de Carvalho, B. Youngman. 


:::

::: {.callout-tip collapse="true" appearance="simple" icon=false}
# <span style="color: rgb(25,188,156)">21/03/25</span>  GPDFlow: Generative Multivariate Threshold Exceedance Modeling via Normalizing Flows by C. Hu (UofG)

**Summary**
The multivariate generalized Pareto distribution (mGPD) is a common method for modelling extreme threshold exceedance probabilities in environmental and financial risk management. Despite its broad applicability, mGPD faces challenges due to the infinite possible parametrizations of its dependence function, with only a few parametric models available in practice. To address this limitation, we introduce GPDFlow, an innovative mGPD model that leverages normalizing flows to flexibly represent the dependence structure. Unlike traditional parametric mGPD approaches, GPDFlow does not impose explicit parametric assumptions on dependence, resulting in greater flexibility and enhanced performance. Additionally, GPDFlow allows direct inference of marginal parameters, providing insights into marginal tail behaviour. We derive tail dependence coefficients for GPDFlow, including a bivariate formulation, a d-dimensional extension, and an alternative measure for partial exceedance dependence. A general relationship between the bivariate tail dependence coefficient and the generative samples from normalizing flows is discussed. Through simulations and a practical application analyzing the risk among five major US banks, we demonstrate that GPDFlow significantly improves modelling accuracy and flexibility compared to traditional parametric methods.

 
**Joint work with:** Daniela Castro-Camilo (UofG). 


:::

::: {.callout-tip collapse="true" appearance="simple" icon=false}
# <span style="color: rgb(25,188,156)">21/03/25</span> Data fusion and extremes: a match made in Bayesian heaven by D. Castro-Camilo (UofG)

**Summary**
Data fusion models are increasingly used to combine in situ and remote-sensing data, providing a more complete and temporally detailed picture of environmental conditions. However, traditional Gaussian-based models tend to underestimate extreme pollution events, which can lead to inaccurate risk assessments. To tackle this, we introduce a Bayesian hierarchical framework for data fusion grounded in extreme value theory. Our approach employs the Dirac-delta generalised Pareto distribution, allowing us to model both threshold and non-threshold exceedances while maintaining the temporal structure of extreme events. We apply this model to predict and describe censored threshold exceedances of PM2.5 pollution across Greater London, using remote sensing data from the EAC4 dataset (part of the Copernicus Atmospheric Monitoring Service) alongside in situ measurements from the UK's Automatic Urban and Rural Network (AURN). Key contributions of our approach lie in our model's ability to (1) preserve the temporal structure of both extreme and non-extreme events, (2) seamlessly integrate data with varying spatio-temporal resolutions while fully accounting for parameter uncertainties, and (3) generate a complete spatio-temporal dataset that calibrates remote-sensing observations to accurately capture local threshold exceedances, guided by in situ measurements. Our results demonstrate that the new approach outperforms both Gaussian-based models and standalone remote-sensing data, providing more accurate predictions of threshold exceedances. In fact, it reveals finer spatial patterns of PM2.5 pollution, such as higher concentrations near coastal areas, which were not captured by remote sensing data alone.

 
**Joint work with:** M. Daniela Cuba (Agricarbon, UofG), Craig Wilkie (UofG) and Marian Scott (UofG). 


:::


::: {.callout-tip collapse="true" appearance="simple" icon=false}
# <span style="color: rgb(25,188,156)">14/02/25</span> Radial generalized Pareto distributions for extreme multivariate risk by I. Papastathopoulos (UofE)

**Summary**
We introduce a novel class of multivariate distributions, termed radial generalized Pareto distributions, which emerge as non-degenerate limits of radially recentered and rescaled exceedances above direction-dependent thresholds. This framework leverages a novel convergence to Poisson point processes for multivariate extremes, providing an overarching stochastic foundation for constructing distributions that exhibit stability properties, enabling extrapolation of risk in any direction within multivariate spaces. Our framework naturally leads to the notion of quantile and return sets which closely parallel related notions of quantile regions that are based on optimal transport approaches, but also leads to isotropic return sets that are exceeded with equal probability along any direction.

We develop a fully Bayesian inference framework for these multivariate distributions, utilising latent Gaussian processes. We also construct novel diagnostics for assessing the convergence to the limit distribution and validate our methods through simulations. Our methods are also applied to real-world data from hydrology and oceanography, demonstrating their broad applicability in risk analysis and their potential to inform decision-making in the presence of extreme events.

 
**Joint work with:** Lambert De Monte (University of Edinburgh), Ryan Campbell (Lancaster University) and Haavard Rue (KAUST). 


:::

::: {.callout-tip collapse="true" appearance="simple" icon=false}
# <span style="color: rgb(25,188,156)">15/11/25</span>  A Kolmogorov–Arnold Neural Model for Cascading Extremes by M. de Carvalho (UofE)

**Summary**
In this talk I will address the growing concern of cascading extreme events, such as a tsunami followed by an extreme earthquake, by presenting a novel method for risk assessment focused on these domino effects. The proposed method develops an extreme value theory framework within a Kolmogorov–Arnold Neural Network (KAN) to estimate the probability of one extreme event triggering another, as a function of a covariate or feature vector. Our approach is backed by exhaustive numerical studies and illustrated on a real-life application to seismology.
 
**Joint work with:** C. Ferrer and R. Vallejos.

**Slides:** [click here](https://drive.google.com/file/d/1LJpaUfIW2VKoZSTcaeCRYJ9n9bsdZeEg/view?usp=sharing)
:::

::: {.callout-tip collapse="true" appearance="simple" icon=false}
# <span style="color: rgb(25,188,156)">18/10/24</span> A deep learning approach to modelling joint environmental extremes by J. Richards (UofE)

**Summary**
he geometric representation for multivariate extremes, where data is split into radial and angular components and the radial component is modelled conditionally on the angle, provides an exciting new approach to modelling environmental data. Through a consideration of scaled sample clouds and limit sets, it provides a flexible, semi-parametric model for extremes that connects multiple classical extremal dependence measures; these include the coefficients of tail dependence and asymptotic independence, and parameters of the conditional extremes framework. Although the geometric approach is becoming an increasingly popular modelling tool for environmental data, its inference is limited to a low dimensional setting (d ≤ 3). 
 
We propose here the first deep representation for geometric extremes. By leveraging the predictive power and computational scalability of neural networks, we construct asymptotically-justified yet flexible semi-parametric models for extremal dependence of high-dimensional data. We showcase the efficacy of our deep approach by modelling the complex extremal dependence between metocean variables sampled from the North Sea.
 
**Joint work with:** Callum JR Murphy-Barltrop and Reetam Majumder

**Slides:** [click here](https://drive.google.com/file/d/1ssAh5rKhkt2KG2Wb0cwr2LU_q8GSSHVX/view?usp=sharing)
:::
