---
title: "Workshop 2025"
---

GLE$^2$N will host its first in-person workshop in December 2025 at the University of Glasgow, marking the one-year anniversary of the network.

This one-day event will bring together researchers in extreme value theory (EVT) and statistical risk analysis, with a particular focus on:


- Advances in EVT **theory**, **methodology**, and **real-world impact**,

- Applications to climate, environment, health, and finance,

- Emerging challenges and opportunities for collaboration across Scotland and beyond.

## Format

Morning: Research talks by invited speakers and GLE$^2$N members.

Afternoon: Thematic andn interactive discussions around open problems and future directions, aimed at fostering new collaborations.

## Goals

The workshop will:

- Strengthen connections across the Scottish and UK EVT community,

- Provide a platform for early-career researchers to present their work and network,

- Highlight the role of EVT in addressing real-world challenges.

## Practical Details

**Date**: Thursday 11 December 2025, 9:00 - 17:00.

**Location**: University of Glasgow.

**Catering**: Refreshments provided, lunch not provided.


## Participation

We anticipate around 25–30 participants, including students, early-career researchers, and established academics from across the UK. If you are interested in attending, please [complete the registration form](https://docs.google.com/forms/d/e/1FAIpQLSc5FsqyhePd6dGF4YAtvcSCbGi2vZ8BBaLicKB_1o9vBR9Oeg/viewform?usp=header). We will do our best to accommodate everyone, but places cannot be guaranteed. A limited budget is available to support student and ECR participation. If you would like to be considered for this support, please indicate so in the relevant section of the form.

👉 Check this page for updates on programme and speakers.

